### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by tapiab** [AirbusDefenceAndSpace/pesto#35]
PESTO documentation ( https://airbusdefenceandspace.github.io/pesto/ ) is broken

**Comment by fchouteau** [comment]
Seems to be just the index.html that does not redirect to anything, however the rest of the documentation seems to be working fine

**Comment by tapiab** [comment]
Thanks! Fix proposed [here](https://github.com/AirbusDefenceAndSpace/pesto/pull/36)
