### ISSUE TITLE
Wrong wheel name in Dockerfile

### ISSUE THREAD

**Issue by gpo-geo** [AirbusDefenceAndSpace/pesto#7]
https://github.com/AirbusDefenceAndSpace/pesto/blob/d8be06d58d5c7869d12b14559c9175c8fef2d298/pesto-cli/pesto/cli/resources/Dockerfile#L44

Now that pesto wheel is renamed "processing_factory-1.2.0-py3-none-any.whl", this line fails to find pesto during service build.

Suggested change:

`RUN  if test   -e /opt/tmp/pesto/dist/*.whl; then pip install /opt/tmp/pesto/dist/*.whl; fi`

**Comment by vgreiner** [comment]
This issue is now fixed in v1.2.1
